// examples/virtual/react/list/horizontal/src/code.tsx
import { memo } from "react";
import { useVirtual, List, ListItemProps } from "@af-utils/virtual-react";
import css from "./style.module.css";

const Item = memo<ListItemProps>(({ i, model }) => (
    <div
        ref={el => model.el(i, el)}
        className={i % 2 ? css.oddItem : css.evenItem}
    >
        col&nbsp;{i}
    </div>
));

const HorizontalList = () => {
    const cols = useVirtual({
        itemCount: 50000,
        estimatedItemSize: 75,
        horizontal: true
    });

    return (
        <List model={cols} className={css.list}>
            {Item}
        </List>
    );
};

export default HorizontalList;

// examples/src/virtual/list/horizontal/svelte/src/code.svelte
<script lang="ts">
    import {
        createVirtual,
        createVirtualList,
        virtualItem
    } from "@af-utils/virtual-svelte";
    import css from "./style.module.css";

    const columns = createVirtual({
        itemCount: 50_000,
        estimatedItemSize: 75,
        horizontal: true
    });
    const { range, scroller, size, items } = createVirtualList(columns);
</script>

<div use:scroller>
    <div use:size>
        <div use:items>
            {#each $range as index (index)}
                <div
                    use:virtualItem={{ model: columns, index }}
                    class={index % 2 ? css.oddItem : css.evenItem}
                >
                    col&nbsp;{index}
                </div>
            {/each}
        </div>
    </div>
</div>
