// examples/src/virtual/primitives/different-scroll-element/vue/src/code.vue
<script setup lang="ts">
import { mapVirtualRange, VirtualScrollerEvent } from "@af-utils/virtual-core";
import {
    useVirtual,
    useVirtualLayout,
    useVirtualSnapshot,
    virtualItemDirective as vVirtualItem
} from "@af-utils/virtual-vue";
import { computed } from "vue";
import css from "./style.module.css";

const model = useVirtual({ itemCount: 5_000 });
const layout = useVirtualLayout(model);
const revision = useVirtualSnapshot(model, VirtualScrollerEvent.RANGE);
const indexes = computed(() => {
    void revision.value;
    return mapVirtualRange(model, index => index);
});
</script>

<template>
    <div
        :ref="layout.scrollerRef"
        :class="css.list"
        :style="layout.scrollerStyle"
        role="list"
    >
        <div :class="css.offset1">Some offset</div>
        <div>
            <div :class="css.offset2">Some offset 2</div>
            <div>
                <div :ref="layout.sizeRef" :style="layout.sizeStyle">
                    <div :ref="layout.itemsRef" :style="layout.itemsStyle">
                        <div
                            v-for="index in indexes"
                            :key="index"
                            v-virtual-item="[model, index]"
                            :class="css.item"
                            role="listitem"
                        >
                            row {{ index }}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</template>

// examples/src/virtual/solid/primitives/simple/src/code.tsx
import { mapVirtualRange, VirtualScrollerEvent } from "@af-utils/virtual-core";
import {
    createVirtual,
    createVirtualItemRef,
    createVirtualLayout,
    createVirtualSnapshot
} from "@af-utils/virtual-solid";
import { createMemo, For } from "solid-js";
import css from "./style.module.css";

const PrimitiveList = () => {
    const model = createVirtual({ itemCount: 50_000 });
    const layout = createVirtualLayout(model);
    const revision = createVirtualSnapshot(model, VirtualScrollerEvent.RANGE);
    const indexes = createMemo(() => {
        revision();
        return mapVirtualRange(model, index => index);
    });

    return (
        <div
            ref={layout.scrollerRef}
            style={layout.scrollerStyle}
            class={css.list}
            role="list"
            aria-label="Solid primitive virtual list"
        >
            <div ref={layout.sizeRef} style={layout.sizeStyle}>
                <div ref={layout.itemsRef} style={layout.itemsStyle}>
                    <For each={indexes()}>
                        {index => (
                            <div
                                ref={createVirtualItemRef(model, index)}
                                class={css.item}
                                role="listitem"
                                aria-posinset={index + 1}
                                aria-setsize={model.itemCount}
                            >
                                row {index}
                            </div>
                        )}
                    </For>
                </div>
            </div>
        </div>
    );
};

export default PrimitiveList;
