// examples/src/virtual/react/list/scroll-to-item/src/code.tsx
import { useState, memo, useEffect } from "react";
import { useVirtual, List, useVirtualItemRef } from "@af-utils/virtual-react";
import { VirtualScroller } from "@af-utils/virtual-core";
import type { ListItemProps } from "@af-utils/virtual-react";
import type { FormEvent } from "react";
import css from "./style.module.css";

const DEFAULT_ROW_COUNT = 50000;

const Item = memo<ListItemProps<number[]>>(({ model, index, data }) => (
    <div
        ref={useVirtualItemRef(model, index)}
        className={css.item}
        role="listitem"
        aria-posinset={index + 1}
        aria-setsize={data!.length}
        style={{
            padding: `${data![index]}px 0.7em`
        }}
    >
        row {index}:&nbsp;{data![index]}px
    </div>
));

const getScrollSubmitHandler =
    (model: VirtualScroller) => (e: FormEvent<HTMLFormElement>) => {
        e.preventDefault();
        const idx = Number.parseInt(e.currentTarget.idx.value, 10);

        if (!Number.isNaN(idx)) {
            model.scrollToIndex(idx, true);
        }
    };

const ScrollToItem = () => {
    const [pseudoRandomSizes, changeRows] = useState(() =>
        Array.from(
            { length: DEFAULT_ROW_COUNT },
            (_, i) => 20 + ((i ** 2) & 31)
        )
    );

    const model = useVirtual({
        itemCount: pseudoRandomSizes.length,
        estimatedItemSize: 75
    });

    useEffect(() => {
        model.scrollToIndex(pseudoRandomSizes.length - 1);
    }, [model, pseudoRandomSizes.length]);

    const rowsAddSubmitHandler = (e: FormEvent<HTMLFormElement>) => {
        e.preventDefault();
        const rowsToAdd = Number.parseInt(e.currentTarget.rowsToAdd.value, 10);

        if (!Number.isNaN(rowsToAdd) && rowsToAdd !== 0) {
            changeRows(rows =>
                rowsToAdd > 0
                    ? rows.concat(
                          Array.from(
                              { length: rowsToAdd },
                              (_, i) => 50 + ((i ** 2) & 63)
                          )
                      )
                    : rows.slice(0, rowsToAdd)
            );
        } else {
            model.scrollToIndex(pseudoRandomSizes.length - 1);
        }
    };

    return (
        <List
            model={model}
            itemData={pseudoRandomSizes}
            role="list"
            header={
                <form
                    className={`${css.form} ${css.top0}`}
                    ref={el => model.setStickyHeader(el)}
                    onSubmit={getScrollSubmitHandler(model)}
                >
                    <label>
                        Smooth scroll to index:&nbsp;
                        <input
                            required
                            defaultValue={Math.round(
                                pseudoRandomSizes.length / 2
                            )}
                            name="idx"
                            className={css.inp}
                            type="number"
                        />
                    </label>
                    <button className={css.btn} type="submit">
                        Go
                    </button>
                </form>
            }
            footer={
                <form
                    ref={el => model.setStickyFooter(el)}
                    className={`${css.form} ${css.bottom0}`}
                    onSubmit={rowsAddSubmitHandler}
                >
                    <label>
                        Rows to add:&nbsp;
                        <input
                            defaultValue={0}
                            type="number"
                            required
                            name="rowsToAdd"
                            className={css.inp}
                        />
                    </label>

                    <button className={css.btn} type="submit">
                        Add and scroll to end
                    </button>
                </form>
            }
        >
            {Item}
        </List>
    );
};

export default ScrollToItem;

// examples/src/virtual/list/scroll-to-item/solid/src/code.tsx
import type { VirtualScroller } from "@af-utils/virtual-core";
import {
    createVirtual,
    createVirtualItemRef,
    List,
    type ListItemProps
} from "@af-utils/virtual-solid";
import { createEffect, createSignal } from "solid-js";
import css from "./style.module.css";

const DEFAULT_ROW_COUNT = 50_000;

const Item = (props: ListItemProps<number[]>) => (
    <div
        ref={createVirtualItemRef(props.model, props.index)}
        class={css.item}
        role="listitem"
        aria-posinset={props.index + 1}
        aria-setsize={props.data?.length}
        style={{ padding: `${props.data?.[props.index]}px 0.7em` }}
    >
        row {props.index}:&nbsp;{props.data?.[props.index]}px
    </div>
);

const scrollFromForm = (model: VirtualScroller, form: HTMLFormElement) => {
    const index = Number.parseInt(
        String(new FormData(form).get("index") ?? ""),
        10
    );
    if (!Number.isNaN(index)) model.scrollToIndex(index, true);
};

const ScrollToItem = () => {
    const [sizes, setSizes] = createSignal(
        Array.from(
            { length: DEFAULT_ROW_COUNT },
            (_, index) => 20 + ((index ** 2) & 31)
        )
    );
    const model = createVirtual(() => ({
        itemCount: sizes().length,
        estimatedItemSize: 78
    }));

    createEffect(() => model.scrollToIndex(sizes().length - 1));

    const changeRows = (form: HTMLFormElement) => {
        const rowsToAdd = Number.parseInt(
            String(new FormData(form).get("rowsToAdd") ?? ""),
            10
        );
        if (!Number.isNaN(rowsToAdd) && rowsToAdd !== 0) {
            setSizes(current =>
                rowsToAdd > 0
                    ? current.concat(
                          Array.from(
                              { length: rowsToAdd },
                              (_, index) => 50 + ((index ** 2) & 63)
                          )
                      )
                    : current.slice(0, rowsToAdd)
            );
        } else {
            model.scrollToIndex(sizes().length - 1);
        }
    };

    return (
        <List
            class={css.list}
            model={model}
            itemData={sizes()}
            role="list"
            header={
                <form
                    class={`${css.form} ${css.top0}`}
                    ref={element => model.setStickyHeader(element)}
                    onSubmit={event => {
                        event.preventDefault();
                        scrollFromForm(model, event.currentTarget);
                    }}
                >
                    <label>
                        Smooth scroll to index:&nbsp;
                        <input
                            required
                            value={Math.round(sizes().length / 2)}
                            name="index"
                            class={css.inp}
                            type="number"
                        />
                    </label>
                    <button class={css.btn} type="submit">
                        Go
                    </button>
                </form>
            }
            footer={
                <form
                    ref={element => model.setStickyFooter(element)}
                    class={`${css.form} ${css.bottom0}`}
                    onSubmit={event => {
                        event.preventDefault();
                        changeRows(event.currentTarget);
                    }}
                >
                    <label>
                        Rows to add:&nbsp;
                        <input
                            value={0}
                            type="number"
                            required
                            name="rowsToAdd"
                            class={css.inp}
                        />
                    </label>
                    <button class={css.btn} type="submit">
                        Add and scroll to end
                    </button>
                </form>
            }
        >
            {Item}
        </List>
    );
};

export default ScrollToItem;
