// packages/virtual/solid/src/components/List/index.tsx
import { mapVirtualRange, VirtualScrollerEvent } from "@af-utils/virtual-core";
import { createMemo, For, splitProps } from "solid-js";
import createVirtualLayout from "../../primitives/createVirtualLayout";
import createVirtualSnapshot from "../../primitives/createVirtualSnapshot";
import type { ListItemProps, ListProps } from "../../types";

/**
 * Render a virtual Solid list with model-owned DOM geometry.
 *
 * @public
 */
const List = <Data = unknown>(props: ListProps<Data>) => {
    const [local, rest] = splitProps(props, [
        "model",
        "children",
        "itemData",
        "header",
        "footer",
        "style",
        "tabIndex"
    ]);
    const layout = createVirtualLayout(local.model, local.style);
    const revision = createVirtualSnapshot(
        local.model,
        VirtualScrollerEvent.RANGE
    );
    const indexes = createMemo(() => {
        revision();
        return mapVirtualRange(local.model, index => index);
    });

    /** Render one range index with live access to optional item data. */
    const renderItem = (index: number) => {
        const itemProps: ListItemProps<Data> = {
            model: local.model,
            index,
            get data() {
                return local.itemData;
            }
        };

        return local.children(itemProps);
    };

    return (
        <div
            {...rest}
            ref={layout.scrollerRef}
            style={layout.scrollerStyle}
            tabIndex={local.tabIndex ?? -1}
        >
            {local.header}
            <div ref={layout.sizeRef} style={layout.sizeStyle}>
                <div ref={layout.itemsRef} style={layout.itemsStyle}>
                    <For each={indexes()}>{renderItem}</For>
                </div>
            </div>
            {local.footer}
        </div>
    );
};

export default List;

// packages/virtual/preact/src/components/List/index.tsx
import { mapVirtualRange, VirtualScrollerEvent } from "@af-utils/virtual-core";
import type { ComponentType } from "preact";
import useVirtualLayout from "../../hooks/useVirtualLayout";
import useVirtualSnapshot from "../../hooks/useVirtualSnapshot";
import type { ListItemProps, ListProps } from "../../types";

/** Render only the model-owned range while isolating its subscriptions. */
const VirtualItems = <Data,>({
    model,
    Item,
    data,
    getKey
}: {
    model: ListItemProps<Data>["model"];
    Item: ComponentType<ListItemProps<Data>>;
    data: Data | undefined;
    getKey: (index: number, data: Data) => string | number;
}) => {
    useVirtualSnapshot(model, VirtualScrollerEvent.RANGE);
    return mapVirtualRange(model, index => (
        <Item
            key={getKey(index, data as Data)}
            model={model}
            index={index}
            data={data}
        />
    ));
};

/** Render a virtual Preact list with model-owned DOM geometry. @public */
const List = <Data = unknown,>(props: ListProps<Data>) => {
    const {
        model,
        children: Item,
        itemData,
        header,
        footer,
        getKey = index => index,
        tabIndex = -1,
        style,
        ...rest
    } = props;
    const layout = useVirtualLayout(model, style);

    return (
        <div
            {...rest}
            ref={layout.scrollerRef}
            style={layout.scrollerStyle}
            tabIndex={tabIndex}
        >
            {header}
            <div ref={layout.sizeRef} style={layout.sizeStyle}>
                <div ref={layout.itemsRef} style={layout.itemsStyle}>
                    <VirtualItems
                        model={model}
                        Item={Item}
                        data={itemData}
                        getKey={getKey}
                    />
                </div>
            </div>
            {footer}
        </div>
    );
};

export default List;
