// examples/src/virtual/data-changes/load-on-demand/preact/src/code.tsx
import { VirtualScrollerEvent } from "@af-utils/virtual-core";
import type { ListItemProps } from "@af-utils/virtual-preact";
import {
    VirtualList,
    useVirtual,
    useVirtualEffect,
    useVirtualItemRef
} from "@af-utils/virtual-preact";
import { memo, useCallback, useRef, useState } from "preact/compat";
import css from "./style.module.css";

const descriptionParts = [
    "Virtualized content stays responsive as the collection grows.",
    "Only the visible range is mounted and measured.",
    "This deterministic text keeps framework screenshots comparable."
];

const createDescriptions = (start: number) => {
    const descriptions: string[] = [];

    for (let offset = 0; offset < 5; offset++) {
        const parts: string[] = [];
        const partCount = 1 + ((start + offset) % descriptionParts.length);

        for (let part = 0; part < partCount; part++) {
            parts.push(
                descriptionParts[
                    (start + offset + part) % descriptionParts.length
                ]
            );
        }
        descriptions.push(parts.join(" "));
    }

    return descriptions;
};

const fetchDescriptions = (start: number) =>
    new Promise<string[]>(resolve => {
        setTimeout(resolve, 200, createDescriptions(start));
    });

const Item = memo<ListItemProps<string[]>>(({ model, index, data }) => {
    const posts = data as string[];

    return (
        <div
            ref={useVirtualItemRef(model, index)}
            className={css.item}
            role="listitem"
            aria-posinset={index + 1}
            aria-setsize={model.itemCount}
        >
            <div className={css.itemHeader}>some picture</div>
            <p>{posts[index]}</p>
        </div>
    );
});

const Posts = () => {
    const [posts, setPosts] = useState(() => createDescriptions(0));

    const isLoadingRef = useRef(false);

    const model = useVirtual({
        itemCount: posts.length,
        estimatedItemSize: 500
    });

    useVirtualEffect(
        model,
        useCallback(async () => {
            if (isLoadingRef.current === false && posts.length === model.to) {
                isLoadingRef.current = true;
                const paragraphs = await fetchDescriptions(posts.length);
                isLoadingRef.current = false;
                setPosts(p => [...p, ...paragraphs]);
            }
        }, [model, posts]),
        VirtualScrollerEvent.RANGE
    );

    return (
        <VirtualList
            model={model}
            itemData={posts}
            role="list"
            aria-label="Load on demand list"
        >
            {Item}
        </VirtualList>
    );
};

export default Posts;

// examples/src/virtual/data-changes/load-on-demand/vue/src/code.vue
<script setup lang="ts">
import { VirtualScrollerEvent } from "@af-utils/virtual-core";
import {
    useVirtual,
    virtualItemDirective as vVirtualItem,
    VirtualList
} from "@af-utils/virtual-vue";
import { onMounted, onUnmounted, ref } from "vue";
import css from "./style.module.css";

const descriptionParts = [
    "Virtualized content stays responsive as the collection grows.",
    "Only the visible range is mounted and measured.",
    "This deterministic text keeps framework screenshots comparable."
];

const createDescriptions = (start: number) =>
    Array.from({ length: 5 }, (_description, offset) =>
        Array.from(
            { length: 1 + ((start + offset) % descriptionParts.length) },
            (_part, part) =>
                descriptionParts[
                    (start + offset + part) % descriptionParts.length
                ]
        ).join(" ")
    );

const fetchDescriptions = (start: number) =>
    new Promise<string[]>(resolve => {
        setTimeout(resolve, 200, createDescriptions(start));
    });

const posts = ref(createDescriptions(0));
const model = useVirtual(() => ({
    itemCount: posts.value.length,
    estimatedItemSize: 500
}));
let loading = false;
let unsubscribe = () => {};

const loadMore = async () => {
    if (loading || posts.value.length !== model.to) return;
    loading = true;
    const paragraphs = await fetchDescriptions(posts.value.length);
    loading = false;
    posts.value.push(...paragraphs);
};

onMounted(() => {
    unsubscribe = model.subscribe(
        () => void loadMore(),
        VirtualScrollerEvent.RANGE
    );
    void loadMore();
});
onUnmounted(() => unsubscribe());
</script>

<template>
    <VirtualList :model="model" role="list" aria-label="Load on demand list">
        <template #default="{ model: itemModel, index }">
            <div
                v-virtual-item="[itemModel, index]"
                :class="css.item"
                role="listitem"
                :aria-posinset="index + 1"
                :aria-setsize="itemModel.itemCount"
            >
                <div :class="css.itemHeader">some picture</div>
                <p>{{ posts[index] }}</p>
            </div>
        </template>
    </VirtualList>
</template>
