// examples/src/virtual/list/prepend-items/solid/src/code.tsx
import {
    createVirtual,
    createVirtualItemRef,
    List,
    type ListItemProps
} from "@af-utils/virtual-solid";
import { createSignal } from "solid-js";
import css from "./style.module.css";

const INITIAL_ITEM_COUNT = 10_000;
const PREPEND_BATCH_SIZE = 100;
const SIMULATED_FETCH_DELAY_MS = 500;
const MIN_ITEM_PADDING_PX = 20;
const ITEM_PADDING_VARIANTS = 61;
const ITEM_PADDING_STEP = 37;
const ESTIMATED_ITEM_SIZE_PX = 120;

const createItem = (id: number) => ({
    name: id < 0 ? `Prepended person ${-id}` : `Person ${id}`,
    id,
    height:
        MIN_ITEM_PADDING_PX +
        ((Math.abs(id) * ITEM_PADDING_STEP) % ITEM_PADDING_VARIANTS)
});

type ItemData = ReturnType<typeof createItem>[];

const Item = (props: ListItemProps<ItemData>) => (
    <div
        ref={createVirtualItemRef(props.model, props.index)}
        class={css.item}
        role="listitem"
        aria-posinset={props.index + 1}
        aria-setsize={props.model.itemCount}
        style={{ padding: `${props.data?.[props.index]?.height}px 0.5em` }}
    >
        Idx:&nbsp;{props.index};&emsp;{props.data?.[props.index]?.name}
    </div>
);

const waitForPrependRequest = () =>
    new Promise<void>(resolve => {
        setTimeout(resolve, SIMULATED_FETCH_DELAY_MS);
    });

const PrependItems = () => {
    const [items, setItems] = createSignal(
        Array.from({ length: INITIAL_ITEM_COUNT }, (_, id) => createItem(id))
    );
    const [loading, setLoading] = createSignal(false);
    const model = createVirtual(() => ({
        estimatedItemSize: ESTIMATED_ITEM_SIZE_PX,
        itemCount: items().length
    }));
    let nextPrependedId = -1;

    const prependItems = async () => {
        setLoading(true);
        await waitForPrependRequest();
        const newItems = Array.from({ length: PREPEND_BATCH_SIZE }, () =>
            createItem(nextPrependedId--)
        );
        const desiredScrollPosition = newItems.length + model.visibleFrom;
        model.spliceItems(0, 0, newItems.length);
        setItems(current => [...newItems, ...current]);
        model.scrollToIndex(desiredScrollPosition);
        setLoading(false);
    };

    return (
        <List
            model={model}
            itemData={items()}
            role="list"
            aria-label="Prepend items list"
            header={
                <div
                    class={css.listHeader}
                    ref={element => model.setStickyHeader(element)}
                >
                    <button
                        type="button"
                        class={css.prependButton}
                        onClick={() => void prependItems()}
                        disabled={loading()}
                    >
                        Prepend {PREPEND_BATCH_SIZE} items
                        {loading() ? " (loading...)" : null}
                    </button>
                </div>
            }
        >
            {Item}
        </List>
    );
};

export default PrependItems;

// examples/src/virtual/list/prepend-items/svelte/src/code.svelte
<script lang="ts">
    import {
        createVirtual,
        createVirtualList,
        virtualItem,
        virtualStickyHeader
    } from "@af-utils/virtual-svelte";
    import css from "./style.module.css";

    const INITIAL_ITEM_COUNT = 10_000;
    const PREPEND_BATCH_SIZE = 100;
    const SIMULATED_FETCH_DELAY_MS = 500;
    const MIN_ITEM_PADDING_PX = 20;
    const ITEM_PADDING_VARIANTS = 61;
    const ITEM_PADDING_STEP = 37;
    const ESTIMATED_ITEM_SIZE_PX = 120;

    const createItem = (id: number) => ({
        name: id < 0 ? `Prepended person ${-id}` : `Person ${id}`,
        id,
        height:
            MIN_ITEM_PADDING_PX +
            ((Math.abs(id) * ITEM_PADDING_STEP) % ITEM_PADDING_VARIANTS)
    });
    const waitForPrependRequest = () =>
        new Promise<void>((resolve) => {
            setTimeout(resolve, SIMULATED_FETCH_DELAY_MS);
        });

    let itemData = Array.from({ length: INITIAL_ITEM_COUNT }, (_, id) =>
        createItem(id)
    );
    let loading = false;
    let nextPrependedId = -1;
    const model = createVirtual({
        estimatedItemSize: ESTIMATED_ITEM_SIZE_PX,
        itemCount: itemData.length
    });
    const { range, scroller, size, items } = createVirtualList(model);

    const prependItems = async () => {
        loading = true;
        await waitForPrependRequest();
        const newItems = Array.from({ length: PREPEND_BATCH_SIZE }, () =>
            createItem(nextPrependedId--)
        );
        const desiredScrollPosition = newItems.length + model.visibleFrom;
        model.spliceItems(0, 0, newItems.length);
        itemData = [...newItems, ...itemData];
        model.scrollToIndex(desiredScrollPosition);
        loading = false;
    };
</script>

<div use:scroller role="list" aria-label="Prepend items list">
    <div use:virtualStickyHeader={model} class={css.listHeader}>
        <button
            type="button"
            class={css.prependButton}
            onclick={() => void prependItems()}
            disabled={loading}
        >
            Prepend {PREPEND_BATCH_SIZE} items{loading ? " (loading...)" : ""}
        </button>
    </div>
    <div use:size>
        <div use:items>
            {#each $range as index (itemData[index]?.id ?? index)}
                <div
                    use:virtualItem={{ model, index }}
                    class={css.item}
                    role="listitem"
                    aria-posinset={index + 1}
                    aria-setsize={model.itemCount}
                    style:padding={`${itemData[index]?.height}px 0.5em`}
                >
                    Idx:&nbsp;{index};&emsp;{itemData[index]?.name}
                </div>
            {/each}
        </div>
    </div>
</div>
