// examples/src/virtual/primitives/different-scroll-element/vue/src/code.vue
<script setup lang="ts">
import { mapVirtualRange, VirtualScrollerEvent } from "@af-utils/virtual-core";
import {
    useVirtual,
    useVirtualLayout,
    useVirtualSnapshot,
    virtualItemDirective as vVirtualItem
} from "@af-utils/virtual-vue";
import { computed } from "vue";
import css from "./style.module.css";

const model = useVirtual({ itemCount: 5_000 });
const layout = useVirtualLayout(model);
const revision = useVirtualSnapshot(model, VirtualScrollerEvent.RANGE);
const indexes = computed(() => {
    void revision.value;
    return mapVirtualRange(model, index => index);
});
</script>

<template>
    <div :ref="layout.scrollerRef" :class="css.list" role="list">
        <div :class="css.offset1">Some offset</div>
        <div>
            <div :class="css.offset2">Some offset 2</div>
            <div>
                <div :ref="layout.sizeRef">
                    <div :ref="layout.itemsRef">
                        <div
                            v-for="index in indexes"
                            :key="index"
                            v-virtual-item="[model, index]"
                            :class="css.item"
                            role="listitem"
                        >
                            row {{ index }}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</template>

// examples/src/virtual/primitives/different-scroll-element/react/src/code.tsx
import {
    mapVirtualRange,
    type VirtualScroller,
    VirtualScrollerEvent
} from "@af-utils/virtual-core";
import type { ListItemProps } from "@af-utils/virtual-react";
import {
    useVirtual,
    useVirtualItemRef,
    useVirtualLayout,
    useVirtualSnapshot
} from "@af-utils/virtual-react";
import { memo } from "react";
import css from "./style.module.css";

const Item = memo<ListItemProps>(({ model, index }) => (
    <div
        ref={useVirtualItemRef(model, index)}
        className={css.item}
        role="listitem"
    >
        row {index}
    </div>
));

const Items = ({ model }: { model: VirtualScroller }) => {
    useVirtualSnapshot(model, VirtualScrollerEvent.RANGE);
    return mapVirtualRange(model, index => (
        <Item key={index} model={model} index={index} />
    ));
};

const DifferentScrollElementHook = () => {
    const model = useVirtual({
        itemCount: 5000
    });

    const { sizeRef, itemsRef } = useVirtualLayout(model);

    return (
        <div className={css.list} ref={el => model.setScroller(el)} role="list">
            <div className={css.offset1}>Some offset</div>
            <div>
                <div className={css.offset2}>Some offset 2</div>
                <div>
                    <div ref={sizeRef}>
                        <div ref={itemsRef}>
                            <Items model={model} />
                        </div>
                    </div>
                </div>
            </div>
        </div>
    );
};

export default DifferentScrollElementHook;
