// examples/src/virtual/scrolling/window-scroll/svelte/src/code.svelte
<svelte:options runes={true} />

<script lang="ts">
    import { createVirtualList, virtualItem } from "@af-utils/virtual-svelte";
    import css from "./style.module.css";

    const { model, range, size, items } = createVirtualList({
        itemCount: 5_000
    });

    $effect(() => {
        model.setScroller(window);
        return () => model.setScroller(null);
    });
</script>

<div class={css.offset1}>Some offset</div>
<div>
    <div class={css.offset2}>Some offset 2</div>
    <div>
        <div {@attach size} role="list" aria-label="Window virtual list">
            <div {@attach items}>
                {#each range() as index (index)}
                    <div
                        {@attach virtualItem(model, () => index)}
                        class={css.item}
                        role="listitem"
                        aria-posinset={index + 1}
                        aria-setsize={model.itemCount}
                    >
                        row {index}
                    </div>
                {/each}
            </div>
        </div>
    </div>
</div>

// examples/src/virtual/primitives/different-scroll-element/react/src/code.tsx
import {
    mapVirtualRange,
    type VirtualScroller,
    VirtualScrollerEvent
} from "@af-utils/virtual-core";
import type { ListItemProps } from "@af-utils/virtual-react";
import {
    useVirtual,
    useVirtualItemRef,
    useVirtualLayout,
    useVirtualSnapshot
} from "@af-utils/virtual-react";
import { memo } from "react";
import css from "./style.module.css";

const Item = memo<ListItemProps>(({ model, index }) => (
    <div
        ref={useVirtualItemRef(model, index)}
        className={css.item}
        role="listitem"
    >
        row {index}
    </div>
));

const Items = ({ model }: { model: VirtualScroller }) => {
    useVirtualSnapshot(model, VirtualScrollerEvent.RANGE);
    return mapVirtualRange(model, index => (
        <Item key={index} model={model} index={index} />
    ));
};

const DifferentScrollElementHook = () => {
    const model = useVirtual({
        itemCount: 5000
    });

    const { sizeRef, itemsRef } = useVirtualLayout(model);

    return (
        <div className={css.list} ref={el => model.setScroller(el)} role="list">
            <div className={css.offset1}>Some offset</div>
            <div>
                <div className={css.offset2}>Some offset 2</div>
                <div>
                    <div ref={sizeRef}>
                        <div ref={itemsRef}>
                            <Items model={model} />
                        </div>
                    </div>
                </div>
            </div>
        </div>
    );
};

export default DifferentScrollElementHook;
