// examples/src/virtual/basics/sticky-header-and-footer/vue/src/code.vue
<script setup lang="ts">
import {
    useVirtual,
    virtualItemDirective as vVirtualItem,
    VirtualList,
    type VirtualVueElementRef
} from "@af-utils/virtual-vue";
import css from "./style.module.css";

const rows = useVirtual({ itemCount: 200_000 });
const headerRef: VirtualVueElementRef = element =>
    rows.setStickyHeader(element instanceof HTMLElement ? element : null);
const footerRef: VirtualVueElementRef = element =>
    rows.setStickyFooter(element instanceof HTMLElement ? element : null);
</script>

<template>
    <VirtualList
        :model="rows"
        role="list"
        aria-label="Sticky header and footer list"
    >
        <template #header>
            <div
                :ref="headerRef"
                :class="css.header"
                data-testid="sticky-header"
            >
                Header
            </div>
        </template>
        <template #default="{ model, index }">
            <div
                v-virtual-item="[model, index]"
                :class="css.item"
                role="listitem"
                :aria-posinset="index + 1"
                :aria-setsize="model.itemCount"
            >
                row {{ index }}
            </div>
        </template>
        <template #footer>
            <div
                :ref="footerRef"
                :class="css.footer"
                data-testid="sticky-footer"
            >
                Footer
            </div>
        </template>
    </VirtualList>
</template>

// examples/src/virtual/basics/sticky-header-and-footer/svelte/src/code.svelte
<svelte:options runes={true} />

<script lang="ts">
    import {
        createVirtualList,
        virtualItem,
        virtualStickyFooter,
        virtualStickyHeader
    } from "@af-utils/virtual-svelte";
    import css from "./style.module.css";

    const {
        model: rows,
        range,
        scroller,
        size,
        items
    } = createVirtualList({
        itemCount: 200_000
    });
</script>

<div {@attach scroller} role="list" aria-label="Sticky header and footer list">
    <div
        {@attach virtualStickyHeader(rows)}
        class={css.header}
        data-testid="sticky-header"
    >
        Header
    </div>
    <div {@attach size}>
        <div {@attach items}>
            {#each range() as index (index)}
                <div
                    {@attach virtualItem(rows, () => index)}
                    class={css.item}
                    role="listitem"
                    aria-posinset={index + 1}
                    aria-setsize={rows.itemCount}
                >
                    row {index}
                </div>
            {/each}
        </div>
    </div>
    <div
        {@attach virtualStickyFooter(rows)}
        class={css.footer}
        data-testid="sticky-footer"
    >
        Footer
    </div>
</div>
