// examples/src/virtual/primitives/simple/solid/src/code.tsx
import { mapVirtualRange, VirtualScrollerEvent } from "@af-utils/virtual-core";
import {
    createVirtual,
    createVirtualItemRef,
    createVirtualLayout,
    createVirtualSnapshot
} from "@af-utils/virtual-solid";
import { createMemo, For } from "solid-js";
import css from "./style.module.css";

const PrimitiveList = () => {
    const model = createVirtual({ itemCount: 50_000 });
    const layout = createVirtualLayout(model);
    const revision = createVirtualSnapshot(model, VirtualScrollerEvent.RANGE);
    const indexes = createMemo(() => {
        revision();
        return mapVirtualRange(model, index => index);
    });

    return (
        <div
            ref={layout.scrollerRef}
            class={css.list}
            role="list"
            aria-label="Simple primitives list"
        >
            <div ref={layout.sizeRef}>
                <div ref={layout.itemsRef}>
                    <For each={indexes()}>
                        {index => (
                            <div
                                ref={createVirtualItemRef(model, index)}
                                class={css.item}
                                role="listitem"
                                aria-posinset={index + 1}
                                aria-setsize={model.itemCount}
                            >
                                row {index}
                            </div>
                        )}
                    </For>
                </div>
            </div>
        </div>
    );
};

export default PrimitiveList;

// examples/src/virtual/basics/simple-primitives/vue/src/code.vue
<script setup lang="ts">
import {
    useVirtual,
    useVirtualLayout,
    useVirtualRange,
    virtualItemDirective as vVirtualItem
} from "@af-utils/virtual-vue";
import css from "./style.module.css";

const model = useVirtual({ itemCount: 50_000 });
const layout = useVirtualLayout(model);
const indexes = useVirtualRange(model);
</script>

<template>
    <div
        :ref="layout.scrollerRef"
        :class="css.list"
        role="list"
        aria-label="Simple primitives list"
    >
        <div :ref="layout.sizeRef">
            <div :ref="layout.itemsRef">
                <div
                    v-for="index in indexes"
                    :key="index"
                    v-virtual-item="[model, index]"
                    :class="css.item"
                    role="listitem"
                    :aria-posinset="index + 1"
                    :aria-setsize="model.itemCount"
                >
                    row {{ index }}
                </div>
            </div>
        </div>
    </div>
</template>
