// examples/src/virtual/custom-layouts/grid/lit/src/code.ts
import {
    mapVirtualRangeWithOffset,
    type VirtualScroller,
    VirtualScrollerEvent
} from "@af-utils/virtual-core";
import { VirtualController, virtualGridItem } from "@af-utils/virtual-lit";
import { html, LitElement, unsafeCSS } from "lit";
import { ref } from "lit/directives/ref.js";
import css from "./style.module.css";
import stylesheet from "./style.module.css?inline";

const SIZE = 50_000;

const scrollModelTo = (model: VirtualScroller, value: string) => {
    const index = Number.parseInt(value, 10);
    if (!Number.isNaN(index)) {
        model.scrollToIndex(index, { behavior: "smooth" });
    }
};

export default class Grid extends LitElement {
    static styles = unsafeCSS(stylesheet);

    private readonly rows = new VirtualController(
        this,
        () => ({
            itemCount: SIZE,
            estimatedItemSize: 120,
            overscanCount: 2
        }),
        VirtualScrollerEvent.ALL
    );
    private readonly columns = new VirtualController(
        this,
        () => ({
            itemCount: SIZE,
            estimatedItemSize: 200,
            overscanCount: 2,
            horizontal: true
        }),
        VirtualScrollerEvent.ALL
    );
    private readonly scrollerRef = (element?: Element) => {
        const scroller = (element as HTMLElement | undefined) ?? null;
        this.rows.model.setScroller(scroller);
        this.columns.model.setScroller(scroller);
    };

    connectedCallback() {
        super.connectedCallback();
        this.style.cssText = "display:grid;width:100%;height:100%";
    }

    private scrollFromForm(event: SubmitEvent) {
        event.preventDefault();
        const form = new FormData(event.currentTarget as HTMLFormElement);
        scrollModelTo(
            form.get("type") === "row" ? this.rows.model : this.columns.model,
            String(form.get("index") ?? "")
        );
    }

    protected render() {
        const rows = this.rows.model;
        const columns = this.columns.model;
        const cells = mapVirtualRangeWithOffset(rows, (row, rowOffset) =>
            mapVirtualRangeWithOffset(columns, (column, columnOffset) => ({
                column,
                columnOffset,
                row,
                rowOffset
            }))
        ).flat();

        return html`<div class=${css.root}>
            <form class=${css.form} @submit=${this.scrollFromForm}>
                <select name="type">
                    <option value="row">Row</option>
                    <option value="col">Col</option>
                </select>
                <input
                    placeholder="index"
                    type="number"
                    name="index"
                    min="0"
                    max=${SIZE - 1}
                    class="w-28"
                />
                <button type="submit" class=${css.btn}>Scroll</button>
            </form>
            <div
                ${ref(this.scrollerRef)}
                class=${css.grid}
                data-testid="virtual-grid"
            >
                <div
                    class=${css.gridItems}
                    style=${`height:${rows.scrollSize}px;width:${columns.scrollSize}px`}
                >
                    ${cells.map(
                        cell => html`<div
                            ${virtualGridItem(
                                rows,
                                cell.row,
                                columns,
                                cell.column
                            )}
                            class=${css.cell}
                            data-row-index=${cell.row}
                            data-column-index=${cell.column}
                            style=${`width:${Math.max(cell.column ** 2 % 256, 190)}px;padding:${Math.max(cell.row ** 2 % 64, 30)}px 0;transform:translateX(${cell.columnOffset}px) translateY(${cell.rowOffset}px)`}
                        >
                            <div class=${css.cellContent}>
                                <span>row:</span
                                >${cell.row}<span>col:</span>${cell.column}
                            </div>
                        </div>`
                    )}
                </div>
            </div>
        </div>`;
    }
}

customElements.define("af-virtual-lit-custom-layouts-grid", Grid);

// examples/src/virtual/primitives/grid/svelte/src/code.svelte
<script lang="ts">
    import {
        mapVirtualRangeWithOffset,
        type VirtualScroller,
        VirtualScrollerEvent
    } from "@af-utils/virtual-core";
    import {
        createVirtual,
        createVirtualSnapshot,
        virtualGridItem
    } from "@af-utils/virtual-svelte";
    import type { Action } from "svelte/action";
    import { derived } from "svelte/store";
    import css from "./style.module.css";

    const SIZE = 50_000;
    const rows = createVirtual({
        itemCount: SIZE,
        estimatedItemSize: 120,
        overscanCount: 2
    });
    const columns = createVirtual({
        itemCount: SIZE,
        estimatedItemSize: 200,
        overscanCount: 2,
        horizontal: true
    });
    const rowRevision = createVirtualSnapshot(rows, VirtualScrollerEvent.ALL);
    const columnRevision = createVirtualSnapshot(
        columns,
        VirtualScrollerEvent.ALL
    );
    const cells = derived([rowRevision, columnRevision], () =>
        mapVirtualRangeWithOffset(rows, (row, rowOffset) =>
            mapVirtualRangeWithOffset(columns, (column, columnOffset) => ({
                column,
                columnOffset,
                row,
                rowOffset
            }))
        ).flat()
    );

    const gridScroller: Action<HTMLElement> = (element) => {
        rows.setScroller(element);
        columns.setScroller(element);
        return {
            destroy() {
                rows.setScroller(null);
                columns.setScroller(null);
            }
        };
    };

    const scrollModelTo = (model: VirtualScroller, value: string) => {
        const index = Number.parseInt(value, 10);
        if (!Number.isNaN(index)) model.scrollToIndex(index, true);
    };
    const submit = (event: SubmitEvent) => {
        event.preventDefault();
        const form = new FormData(event.currentTarget as HTMLFormElement);
        scrollModelTo(
            form.get("type") === "row" ? rows : columns,
            String(form.get("index") ?? "")
        );
    };
</script>

<div class={css.root}>
    <form class={css.form} onsubmit={submit}>
        <select name="type">
            <option value="row">Row</option>
            <option value="col">Col</option>
        </select>
        <input
            placeholder="index"
            type="number"
            name="index"
            min={0}
            max={SIZE - 1}
            class="w-28"
        />
        <button type="submit" class={css.btn}>Scroll</button>
    </form>
    <div class={css.grid} use:gridScroller data-testid="virtual-grid">
        <div
            class={css.gridItems}
            style:height={`${rows.scrollSize}px`}
            style:width={`${columns.scrollSize}px`}
        >
            {#each $cells as cell (`${cell.row}:${cell.column}`)}
                <div
                    use:virtualGridItem={{
                        rows,
                        rowIndex: cell.row,
                        columns,
                        columnIndex: cell.column
                    }}
                    class={css.cell}
                    data-row-index={cell.row}
                    data-column-index={cell.column}
                    style:width={`${Math.max(cell.column ** 2 % 256, 190)}px`}
                    style:padding={`${Math.max(cell.row ** 2 % 64, 30)}px 0`}
                    style:transform={`translateX(${cell.columnOffset}px) translateY(${cell.rowOffset}px)`}
                >
                    <div class={css.cellContent}>
                        <span>row:</span>
                        {cell.row}
                        <span>col:</span>
                        {cell.column}
                    </div>
                </div>
            {/each}
        </div>
    </div>
</div>
