// examples/src/virtual/primitives/grid/react/src/code.tsx
import {
    mapVirtualRangeWithOffset,
    type VirtualScroller,
    VirtualScrollerEvent
} from "@af-utils/virtual-core";

import {
    useVirtual,
    useVirtualGridItemRef,
    useVirtualSnapshot
} from "@af-utils/virtual-react";
import { Fragment, memo } from "react";

import css from "./style.module.css";

const events = VirtualScrollerEvent.ALL;

const Cell = memo<{
    rows: VirtualScroller;
    cols: VirtualScroller;
    rowI: number;
    colI: number;
    rowOffset: number;
    colOffset: number;
}>(({ rows, cols, rowI, colI, rowOffset, colOffset }) => (
    <div
        ref={useVirtualGridItemRef(rows, rowI, cols, colI)}
        className={css.cell}
        data-row-index={rowI}
        data-column-index={colI}
        style={{
            width: Math.max(colI ** 2 % 256, 190),
            padding: `${Math.max(rowI ** 2 % 64, 30)}px 0`,
            transform: `translateX(${colOffset}px) translateY(${rowOffset}px)`
        }}
    >
        <div className={css.cellContent}>
            <span>row:</span>
            {rowI}
            <span>col:</span>
            {colI}
        </div>
    </div>
));

const GridItems = ({
    rows,
    cols
}: {
    rows: VirtualScroller;
    cols: VirtualScroller;
}) => {
    useVirtualSnapshot(rows, events);
    useVirtualSnapshot(cols, events);

    return (
        <div
            className={css.gridItems}
            style={{
                height: rows.scrollSize,
                width: cols.scrollSize
            }}
        >
            {mapVirtualRangeWithOffset(rows, (rowI, rowOffset) => (
                <Fragment key={rowI}>
                    {mapVirtualRangeWithOffset(cols, (colI, colOffset) => (
                        <Cell
                            key={colI}
                            rows={rows}
                            cols={cols}
                            rowOffset={rowOffset}
                            colOffset={colOffset}
                            rowI={rowI}
                            colI={colI}
                        />
                    ))}
                </Fragment>
            ))}
        </div>
    );
};

const SIZE = 50000;

const scrollModelTo = (model: VirtualScroller, value: string | undefined) => {
    if (value !== undefined) {
        const idx = Number.parseInt(value, 10);

        if (!Number.isNaN(idx)) {
            model.scrollToIndex(idx, true);
        }
    }
};

const GridHook = () => {
    const rows = useVirtual({
        itemCount: SIZE,
        estimatedItemSize: 120,
        overscanCount: 2
    });

    const cols = useVirtual({
        itemCount: SIZE,
        estimatedItemSize: 200,
        overscanCount: 2,
        horizontal: true
    });

    return (
        <div className={css.root}>
            <form
                className={css.form}
                onSubmit={e => {
                    e.preventDefault();
                    scrollModelTo(
                        e.currentTarget.type.value === "row" ? rows : cols,
                        e.currentTarget.index.value
                    );
                }}
            >
                <select name="type">
                    <option value="row">Row</option>
                    <option value="col">Col</option>
                </select>
                <input
                    placeholder="index"
                    type="number"
                    name="index"
                    min={0}
                    max={SIZE - 1}
                    className="w-28"
                />
                <button type="submit" className={css.btn}>
                    Scroll
                </button>
            </form>
            <div
                className={css.grid}
                data-testid="virtual-grid"
                ref={el => {
                    rows.setScroller(el);
                    cols.setScroller(el);
                }}
            >
                <GridItems rows={rows} cols={cols} />
            </div>
        </div>
    );
};

export default GridHook;

// examples/src/virtual/primitives/grid/svelte/src/code.svelte
<script lang="ts">
    import {
        mapVirtualRangeWithOffset,
        type VirtualScroller,
        VirtualScrollerEvent
    } from "@af-utils/virtual-core";
    import {
        createVirtual,
        createVirtualSnapshot,
        virtualGridItem
    } from "@af-utils/virtual-svelte";
    import type { Action } from "svelte/action";
    import { derived } from "svelte/store";
    import css from "./style.module.css";

    const SIZE = 50_000;
    const rows = createVirtual({
        itemCount: SIZE,
        estimatedItemSize: 120,
        overscanCount: 2
    });
    const columns = createVirtual({
        itemCount: SIZE,
        estimatedItemSize: 200,
        overscanCount: 2,
        horizontal: true
    });
    const rowRevision = createVirtualSnapshot(rows, VirtualScrollerEvent.ALL);
    const columnRevision = createVirtualSnapshot(
        columns,
        VirtualScrollerEvent.ALL
    );
    const cells = derived([rowRevision, columnRevision], () =>
        mapVirtualRangeWithOffset(rows, (row, rowOffset) =>
            mapVirtualRangeWithOffset(columns, (column, columnOffset) => ({
                column,
                columnOffset,
                row,
                rowOffset
            }))
        ).flat()
    );

    const gridScroller: Action<HTMLElement> = (element) => {
        rows.setScroller(element);
        columns.setScroller(element);
        return {
            destroy() {
                rows.setScroller(null);
                columns.setScroller(null);
            }
        };
    };

    const scrollModelTo = (model: VirtualScroller, value: string) => {
        const index = Number.parseInt(value, 10);
        if (!Number.isNaN(index)) model.scrollToIndex(index, true);
    };
    const submit = (event: SubmitEvent) => {
        event.preventDefault();
        const form = new FormData(event.currentTarget as HTMLFormElement);
        scrollModelTo(
            form.get("type") === "row" ? rows : columns,
            String(form.get("index") ?? "")
        );
    };
</script>

<div class={css.root}>
    <form class={css.form} onsubmit={submit}>
        <select name="type">
            <option value="row">Row</option>
            <option value="col">Col</option>
        </select>
        <input
            placeholder="index"
            type="number"
            name="index"
            min={0}
            max={SIZE - 1}
            class="w-28"
        />
        <button type="submit" class={css.btn}>Scroll</button>
    </form>
    <div class={css.grid} use:gridScroller data-testid="virtual-grid">
        <div
            class={css.gridItems}
            style:height={`${rows.scrollSize}px`}
            style:width={`${columns.scrollSize}px`}
        >
            {#each $cells as cell (`${cell.row}:${cell.column}`)}
                <div
                    use:virtualGridItem={{
                        rows,
                        rowIndex: cell.row,
                        columns,
                        columnIndex: cell.column
                    }}
                    class={css.cell}
                    data-row-index={cell.row}
                    data-column-index={cell.column}
                    style:width={`${Math.max(cell.column ** 2 % 256, 190)}px`}
                    style:padding={`${Math.max(cell.row ** 2 % 64, 30)}px 0`}
                    style:transform={`translateX(${cell.columnOffset}px) translateY(${cell.rowOffset}px)`}
                >
                    <div class={css.cellContent}>
                        <span>row:</span>
                        {cell.row}
                        <span>col:</span>
                        {cell.column}
                    </div>
                </div>
            {/each}
        </div>
    </div>
</div>
