// examples/src/virtual/data-changes/live-feed/vue/src/code.vue
<script setup lang="ts">
import {
    useVirtual,
    virtualItemDirective as vVirtualItem,
    VirtualList
} from "@af-utils/virtual-vue";
import { nextTick, onMounted, ref, watch } from "vue";
import css from "./style.module.css";

interface Message {
    id: number;
    padding: number;
    text: string;
}

const INITIAL_COUNT = 200;
const createMessage = (id: number): Message => ({
    id,
    padding: 8 + ((id * 13) % 18),
    text: `Message ${id}`
});

const messages = ref(
    Array.from({ length: INITIAL_COUNT }, (_, id) => createMessage(id))
);
const model = useVirtual(() => ({
    estimatedItemSize: 52,
    itemCount: messages.value.length
}));
const getItemKey = (index: number) => messages.value[index]?.id ?? index;
let shouldFollowEnd = true;

const scrollToEnd = () => model.scrollToIndex(messages.value.length - 1);
const appendMessage = () => {
    shouldFollowEnd = model.to === model.itemCount;
    messages.value.push(createMessage(messages.value.length));
};

watch(
    () => messages.value.length,
    async () => {
        await nextTick();
        if (shouldFollowEnd) scrollToEnd();
    }
);
onMounted(scrollToEnd);
</script>

<template>
    <div :class="css.example">
        <div :class="css.toolbar">
            <button type="button" @click="appendMessage">Append message</button>
            <button type="button" @click="scrollToEnd">Jump to latest</button>
            <output :class="css.status">{{ messages.length }} messages</output>
        </div>
        <VirtualList
            :class="css.list"
            :model="model"
            :get-item-key="getItemKey"
            role="list"
            aria-label="Live message feed"
        >
            <template #default="{ model: itemModel, index }">
                <div
                    v-virtual-item="[itemModel, index]"
                    :class="css.item"
                    role="listitem"
                    :aria-posinset="index + 1"
                    :aria-setsize="messages.length"
                    :style="{ paddingBlock: `${messages[index].padding}px` }"
                >
                    {{ messages[index].text }}
                </div>
            </template>
        </VirtualList>
    </div>
</template>

// examples/src/virtual/data-changes/live-feed/react/src/code.tsx
import type { ListItemProps } from "@af-utils/virtual-react";
import {
    VirtualList,
    useVirtual,
    useVirtualItemRef
} from "@af-utils/virtual-react";
import { memo, useEffect, useLayoutEffect, useRef, useState } from "react";
import css from "./style.module.css";

interface Message {
    id: number;
    text: string;
    padding: number;
}
const INITIAL_COUNT = 200;
const useBrowserLayoutEffect =
    typeof window === "undefined" ? useEffect : useLayoutEffect;
const createMessage = (id: number): Message => ({
    id,
    text: `Message ${id}`,
    padding: 8 + ((id * 13) % 18)
});

const Item = memo<ListItemProps<Message[]>>(({ model, index, data }) => {
    const messages = data as Message[];
    const message = messages[index];
    return (
        <div
            ref={useVirtualItemRef(model, index)}
            className={css.item}
            role="listitem"
            aria-posinset={index + 1}
            aria-setsize={messages.length}
            style={{ paddingBlock: message.padding }}
        >
            {message.text}
        </div>
    );
});

const LiveFeed = () => {
    const [messages, setMessages] = useState(() =>
        Array.from({ length: INITIAL_COUNT }, (_, id) => createMessage(id))
    );
    const model = useVirtual({
        estimatedItemSize: 52,
        itemCount: messages.length
    });
    const shouldFollowEnd = useRef(true);

    useBrowserLayoutEffect(() => {
        if (shouldFollowEnd.current) {
            model.scrollToIndex(messages.length - 1);
        }
    }, [messages.length, model]);

    const appendMessage = () => {
        shouldFollowEnd.current = model.to === model.itemCount;
        setMessages(current => current.concat(createMessage(current.length)));
    };

    return (
        <div className={css.example}>
            <div className={css.toolbar}>
                <button type="button" onClick={appendMessage}>
                    Append message
                </button>
                <button
                    type="button"
                    onClick={() => model.scrollToIndex(messages.length - 1)}
                >
                    Jump to latest
                </button>
                <output className={css.status}>
                    {messages.length} messages
                </output>
            </div>
            <VirtualList
                className={css.list}
                model={model}
                itemData={messages}
                getItemKey={index => messages[index]?.id ?? index}
                role="list"
                aria-label="Live message feed"
            >
                {Item}
            </VirtualList>
        </div>
    );
};

export default LiveFeed;
