// examples/src/virtual/basics/simple-list/svelte/src/code.svelte
<svelte:options runes={true} />

<script lang="ts">
    import { createVirtualList, virtualItem } from "@af-utils/virtual-svelte";

    const {
        model: rows,
        range,
        scroller,
        size,
        items
    } = createVirtualList({
        itemCount: 150_000
    });
</script>

<div {@attach scroller} role="list" aria-label="Simple virtual list">
    <div {@attach size}>
        <div {@attach items}>
            {#each range() as index (index)}
                <div
                    {@attach virtualItem(rows, () => index)}
                    role="listitem"
                    aria-posinset={index + 1}
                    aria-setsize={rows.itemCount}
                    style="border-top: 2px solid #ccc; padding: 0.6em"
                >
                    row {index}
                </div>
            {/each}
        </div>
    </div>
</div>

// examples/src/virtual/solid/list/simple/src/code.tsx
import {
    createVirtual,
    createVirtualItemRef,
    List,
    type ListItemProps
} from "@af-utils/virtual-solid";

const Item = (props: ListItemProps) => (
    <div
        ref={createVirtualItemRef(props.model, props.index)}
        role="listitem"
        aria-posinset={props.index + 1}
        aria-setsize={props.model.itemCount}
        style={{ "border-top": "2px solid #ccc", padding: "0.6em" }}
    >
        row {props.index}
    </div>
);

const SimpleList = () => {
    const rows = createVirtual({ itemCount: 150_000 });

    return (
        <List model={rows} role="list" aria-label="Solid virtual list">
            {Item}
        </List>
    );
};

export default SimpleList;
